include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.config.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"    
    - "**/*.freezed.dart"
    
linter: 
  rules:
    avoid_positional_boolean_parameters: false
    avoid_bool_literals_in_conditional_expressions: false