name: tvmaze_app
description: A flutter app consuming the TVMaze API.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  dio: ^3.0.10
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.6
  injectable: ^1.0.7 
  json_annotation: ^3.1.1
  logger: ^0.9.4
  retrofit: ^1.3.4+1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.11.0
  freezed: ^0.12.7
  injectable_generator: ^1.0.7
  json_serializable: ^3.5.1
  lint: ^1.2.0
  mockito: ^4.1.4
  retrofit_generator: ^1.4.1+2
  flutter_native_splash: ^0.2.9
  flutter_launcher_icons: ^0.8.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/tvstatic.gif